names:
  - Smelly
  - Fuzzy
  - Wimpy
  - Sneezy
  - Dopey
  - Dizzy
  - Flaky
  - Speedy
  - Pokey
  - Curly
  - Whirly
  - Creepy
  - Crazy
  - Happy
  - Bumpy
  - Blobby
  - Breezy
  - Salty
  - Shaky
  - Scrawny
  - Shaggy
  - Shorty
  - Skinny
  - Slimy
  - Spicy
  - Squealy
  - Sticky
  - Stingy
  - Zany
  - Thirsty
  - Slippery
  - Testy
  - Tiny
  - Witty
  - Baggy
  - Blurry
  - Cheeky
  - Chewy
  - Clammy
  - Crabby
  - Droopy
  - Frumpy
  - Goopy
  - Jumpy
  - Messy
  - Pretty
  - Queasy
  - Sleepy
  - Squeaky
  - Wheezy
  - Whiny
  - Wooly
  - Zippy
  - Wrinkly

surnames:
  - McDuff
  - Smith
  - Wrinkle
  - Williams
  - Brown
  - Davis
  - Answerson
  - Thomas
  - Martinez
  - Garcia
  - Wilson
  - Johnson
  - Jones
  - Harrison
  - Lewis
  - Hernandez
  - Hill
  - Nelson
  - Turner
  - Stewart
  - Rogers
  - Brooks
  - Sanders
  - Simmons
  - Foster
  - Wallace
  - McDonald
  - Tucker
  - Crawford
  - Gordon
  - Henry
  - Burns
  - Ferguson
  - Arnold
  - Wagner
  - Armstrong
  - Cunningham
  - Lawrence
  - Fields
  - McCoy
  - Jensen
  -